### ISSUE TITLE
GET http://localhost:35729/livereload.js net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by kylekatarnls** [bravesheep/live-reload-bundle#1]
Hi,

I follow the install steps, restart symfony with `php bin/console server:run` and was expecting livereload would be running on http://localhost:35729. But it seems not. The `<script>` tag is well added at the end of the body, but the load of livereload.js failed.

Should livereload be installed separatly?

I would love to have the possibility to attach the livereload run to the `php bin/console server:run` command. So my team could benefit it with a simple update of our project.

If it's not planned, I can propose a pull request.

**Comment by kylekatarnls** [comment]
Any news? Is this project still maintained?

**Comment by marlonbaeten** [comment]
The bundle only adds the livereload listener (client) - not a livereload server to a Symfony project. For a livereload server you should look for another option.
